---
- name: Development Tools - Install snapd apt dependency
  become: true
  apt:
    name: "snapd"
    state: present

- name: Development Tools - Install Postman Snap
  become: true
  snap:
    name: "postman"

- name: Development Tools - VSCode, VSCodium, Sublime Text, Redis desktop manager Snaps w/ --classic
  become: true
  snap:
    name: "{{item}}"
    classic: "yes"
  loop:
        #- "code"
      #- "codium"
      #- "sublime-text"
    - "redis-desktop-manager"
