---
## JetBrains Mono Font
- name: Download JetBrains
  get_url:
    url: "{{ jetbrains_mono_url }}-{{ jetbrains_mono_version }}.zip"
    dest: /tmp/
    mode: '0755'

- name: Unarchive font to /usr/share/fonts
  become: true
  unarchive:
    src: /tmp/JetBrainsMono-{{ jetbrains_mono_version }}.zip
    dest: /usr/share/fonts
    remote_src: "yes"

- name: Install font
  command: fc-cache -f -v

- name: Configure fonts - Interface Text
  dconf:
    key: "/org/gnome/desktop/interface/font-name"
    value: "'JetBrains Mono Bold 11'"
    state: present

- name: Configure fonts - Document Text
  dconf:
    key: "/org/gnome/desktop/interface/document-font-name"
    value: "'JetBrains Mono Regular 9'"
    state: present

- name: Configure fonts - Monospace Text
  dconf:
    key: "/org/gnome/desktop/interface/monospace-font-name"
    value: "'JetBrains Mono Regular 12'"
    state: present

- name: Configure fonts - Window Title
  dconf:
    key: "/org/gnome/desktop/wm/preferences/titlebar-font"
    value: "'JetBrains Mono Regular 11'"
    state: present
